/*	EQEmu: EQEmulator

	Copyright (C) 2001-2026 EQEmu Development Team

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/*
# ShowEQ Import Notes:
# ZERO THE FILE first
# perl -pi -e 's/0x[0-9a-fA-F]{4}/0x0000/g' opcodes.conf
# Unknown Mapping:
# OP_Action2 -> OP_Damage
# OP_EnvDamage -> OP_Damage ---> might have been a one time mistake
# Name Differences:
# OP_CancelInvite -> OP_GroupCancelInvite
# OP_GMFind -> OP_FindPersonRequest
# OP_CommonMessage -> OP_ChannelMessage
*/

// A default define makes intellisense not always complain
#ifndef OPCODE
#define OPCODE(name, value)
#endif

//OP_Unknown=0x0000
//OP_ExploreUnknown=0x0000	# used for unknown explorer

// world packets
// Required to reach Char Select:
OPCODE(OP_SendLoginInfo,                  0x7a09)
OPCODE(OP_ApproveWorld,                   0x7499)
OPCODE(OP_LogServer,                      0x7ceb)
OPCODE(OP_SendCharInfo,                   0x00d2)
OPCODE(OP_ExpansionInfo,                  0x590d)
OPCODE(OP_GuildsList,                     0x507a)
OPCODE(OP_EnterWorld,                     0x578f)
OPCODE(OP_PostEnterWorld,                 0x6259)
OPCODE(OP_World_Client_CRC1,              0x0f13)
OPCODE(OP_World_Client_CRC2,              0x4b8d)
OPCODE(OP_World_Client_CRC3,              0x298d)
//OPCODE(OP_SendSpellChecksum,              0x0000)
//OPCODE(OP_SendSkillCapsChecksum,          0x0000)

// Character Select Related:
OPCODE(OP_SendMaxCharacters,              0x5475)
OPCODE(OP_SendMembership,                 0x7acc)
OPCODE(OP_SendMembershipDetails,          0x057b)
OPCODE(OP_CharacterCreateRequest,         0x6773)
OPCODE(OP_CharacterCreate,                0x6bbf)
OPCODE(OP_DeleteCharacter,                0x1808)
OPCODE(OP_RandomNameGenerator,            0x5954)
OPCODE(OP_ApproveName,                    0x56a2)
OPCODE(OP_MOTD,                           0x0c22)
OPCODE(OP_SetChatServer,                  0x1bc5)
OPCODE(OP_SetChatServer2,                 0x7eec)
OPCODE(OP_ZoneServerInfo,                 0x4c44)
OPCODE(OP_WorldComplete,                  0x4493)
OPCODE(OP_WorldUnknown001,                0x2301)
OPCODE(OP_FloatListThing,                 0x46c6)

// Reasons for Disconnect:
OPCODE(OP_ZoneUnavail,                    0x4cb4)
OPCODE(OP_WorldClientReady,               0x23c1)
//OPCODE(OP_CharacterStillInZone,           0x0000)
//OPCODE(OP_WorldChecksumFailure,           0x0000)
//OPCODE(OP_WorldLoginFailed,               0x0000)
//OPCODE(OP_WorldLogout,                    0x0000)
//OPCODE(OP_WorldLevelTooHigh,              0x0000)
//OPCODE(OP_CharInacessable,                0x0000)
//OPCODE(OP_UserCompInfo,                   0x0000)
//OPCODE(OP_SendExeChecksum,                0x0000)
//OPCODE(OP_SendBaseDataChecksum,           0x0000)

// Zone in opcodes
OPCODE(OP_AckPacket,                      0x471d)
OPCODE(OP_ZoneEntry,                      0x5089)
OPCODE(OP_ReqNewZone,                     0x7887)
OPCODE(OP_NewZone,                        0x1795)
OPCODE(OP_ZoneSpawns,                     0x5237)
OPCODE(OP_PlayerProfile,                  0x6506)
OPCODE(OP_TimeOfDay,                      0x5070)
OPCODE(OP_LevelUpdate,                    0x1eec)
OPCODE(OP_Stamina,                        0x2a79)
OPCODE(OP_RequestClientZoneChange,        0x3fcf)
OPCODE(OP_ZoneChange,                     0x2d18)
OPCODE(OP_LockoutTimerInfo,               0x0000)
OPCODE(OP_ZoneServerReady,                0x0000)
OPCODE(OP_ZoneInUnknown,                  0x0000)
OPCODE(OP_LogoutReply,                    0x0000)
OPCODE(OP_PreLogoutReply,                 0x0000)

// Required to fully log in
OPCODE(OP_SpawnAppearance,                0x0971)
OPCODE(OP_ChangeSize,                     0x4707)
OPCODE(OP_TributeUpdate,                  0x5961)
OPCODE(OP_TributeTimer,                   0x073d)
OPCODE(OP_SendTributes,                   0x729b)
OPCODE(OP_RequestGuildTributes,           0x4d5e)
OPCODE(OP_TributeInfo,                    0x4254)
OPCODE(OP_Weather,                        0x661e)
OPCODE(OP_ReqClientSpawn,                 0x35fa)
OPCODE(OP_SpawnDoor,                      0x7291)
OPCODE(OP_GroundSpawn,                    0x6fca)
OPCODE(OP_SendZonepoints,                 0x69a4)
OPCODE(OP_BlockedBuffs,                   0x3033)
OPCODE(OP_RemoveBlockedBuffs,             0x0de7)
OPCODE(OP_ClearBlockedBuffs,              0x34cb)
OPCODE(OP_WorldObjectsSent,               0x5ae2)
OPCODE(OP_SendExpZonein,                  0x5f8e)
OPCODE(OP_SendAATable,                    0x66b5)
OPCODE(OP_ClearAA,                        0x0f50)
OPCODE(OP_ClearLeadershipAbilities,       0x6da5)
OPCODE(OP_RespondAA,                      0x7a27)
OPCODE(OP_UpdateAA,                       0x66f0)
OPCODE(OP_SendAAStats,                    0x43c8)
OPCODE(OP_AAExpUpdate,                    0x7d14)
OPCODE(OP_ExpUpdate,                      0x20ed)
OPCODE(OP_HPUpdate,                       0x2828)
OPCODE(OP_ManaChange,                     0x5467)
OPCODE(OP_TGB,                            0x0876)
OPCODE(OP_SpecialMesg,                    0x0083)
OPCODE(OP_GuildMemberList,                0x12a6)
OPCODE(OP_GuildMOTD,                      0x3e13)
OPCODE(OP_CharInventory,                  0x5ca6)
OPCODE(OP_WearChange,                     0x7994)
OPCODE(OP_ClientUpdate,                   0x7dfc)
OPCODE(OP_ClientReady,                    0x345d)
OPCODE(OP_SetServerFilter,                0x444d)

// Guild Opcodes
OPCODE(OP_GetGuildMOTD,                   0x36e0)
OPCODE(OP_GetGuildMOTDReply,              0x4f1f)
OPCODE(OP_GuildMemberUpdate,              0x69b9)
OPCODE(OP_GuildInvite,                    0x7099)
OPCODE(OP_GuildRemove,                    0x1444)
OPCODE(OP_GuildPeace,                     0x67e3)
OPCODE(OP_SetGuildMOTD,                   0x0b0b)
OPCODE(OP_GuildWar,                       0x1ffb)
OPCODE(OP_GuildLeader,                    0x7e09)
OPCODE(OP_GuildDelete,                    0x3708)
OPCODE(OP_GuildInviteAccept,              0x7053)
OPCODE(OP_GuildDemote,                    0x2d4e)
OPCODE(OP_GuildPromote,                   0x6a98)
OPCODE(OP_GuildPublicNote,                0x5053)
OPCODE(OP_GuildManageBanker,              0x3f35)
OPCODE(OP_GuildBank,                      0x5134)
OPCODE(OP_GuildBankItemList,              0x7850)
OPCODE(OP_SetGuildRank,                   0x0b9c)
OPCODE(OP_GuildUpdate,                    0x2958)
OPCODE(OP_GuildStatus,                    0x7326)
OPCODE(OP_GuildCreate,                    0x76d9)
//OPCODE(OP_GuildOpenGuildWindow,           0x0276)
OPCODE(OP_GuildMemberLevel,               0x1bd3)
OPCODE(OP_GuildMemberRankAltBanker,       0x0b9c)
OPCODE(OP_GuildMemberPublicNote,          0x01f9)
OPCODE(OP_GuildMemberAdd,                 0x2925)
OPCODE(OP_GuildMemberRename,              0x3b26)
OPCODE(OP_GuildMemberDelete,              0x3141)
OPCODE(OP_GuildMemberDetails,             0x69b9)
OPCODE(OP_GuildRenameGuild,               0x61db)
OPCODE(OP_LFGuild,                        0x3165)
OPCODE(OP_GuildDeleteGuild,               0x6dab)

// GM/Guide Opcodes
OPCODE(OP_GMServers,                      0x08c1)
OPCODE(OP_GMBecomeNPC,                    0x3ae1)
OPCODE(OP_GMZoneRequest,                  0x62ac)
OPCODE(OP_GMZoneRequest2,                 0x7e1a)
OPCODE(OP_GMGoto,                         0x7d8e)
OPCODE(OP_GMSearchCorpse,                 0x357c)
OPCODE(OP_GMHideMe,                       0x2fab)
OPCODE(OP_GMDelCorpse,                    0x607e)
OPCODE(OP_GMApproval,                     0x6db5)
OPCODE(OP_GMToggle,                       0x2097)
OPCODE(OP_GMSummon,                       0x486f)
OPCODE(OP_GMEmoteZone,                    0x1cfd)
//OPCODE(OP_GMEmoteWorld,                   0x458e)
OPCODE(OP_GMFind,                         0x4a8f)
OPCODE(OP_GMKick,                         0x26a7)
OPCODE(OP_GMKill,                         0x51d3)
OPCODE(OP_GMNameChange,                   0x035f)
OPCODE(OP_GMLastName,                     0x46ce)

// Misc Opcodes
OPCODE(OP_QueryUCSServerStatus,           0x398f)
OPCODE(OP_InspectRequest,                 0x57bc)
OPCODE(OP_InspectAnswer,                  0x71ac)
OPCODE(OP_InspectMessageUpdate,           0x4d25)
OPCODE(OP_BeginCast,                      0x318f)
OPCODE(OP_ColoredText,                    0x43af)
OPCODE(OP_ConsentResponse,                0x384a)
OPCODE(OP_MemorizeSpell,                  0x217c)
OPCODE(OP_LinkedReuse,                    0x1619)
OPCODE(OP_SwapSpell,                      0x0efa)
OPCODE(OP_CastSpell,                      0x1287)
OPCODE(OP_Consider,                       0x742b)
OPCODE(OP_FormattedMessage,               0x1024)
OPCODE(OP_SimpleMessage,                  0x213f)
OPCODE(OP_Buff,                           0x659c)
OPCODE(OP_Illusion,                       0x312a)
OPCODE(OP_MoneyOnCorpse,                  0x5f44)
OPCODE(OP_RandomReply,                    0x106b)
OPCODE(OP_DenyResponse,                   0x2382)
OPCODE(OP_SkillUpdate,                    0x04c)
OPCODE(OP_GMTrainSkillConfirm,            0x4b64)
OPCODE(OP_RandomReq,                      0x7b10)
OPCODE(OP_Death,                          0x6517)
OPCODE(OP_GMTraining,                     0x1966)
OPCODE(OP_GMEndTraining,                  0x4d6b)
OPCODE(OP_GMTrainSkill,                   0x2a85)
OPCODE(OP_Animation,                      0x7177)
OPCODE(OP_Begging,                        0x6703)
OPCODE(OP_Consent,                        0x1fd1)
OPCODE(OP_ConsentDeny,                    0x7a45)
OPCODE(OP_AutoFire,                       0x241e)
OPCODE(OP_PetCommands,                    0x0159)
OPCODE(OP_PetCommandState,                0x1dc8)
OPCODE(OP_PetHoTT,                        0x794a)
OPCODE(OP_DeleteSpell,                    0x3358)
OPCODE(OP_Surname,                        0x0423)
OPCODE(OP_ClearSurname,                   0x3fb0)
OPCODE(OP_FaceChange,                     0x5578)
OPCODE(OP_SetFace,                        0x1af3)
OPCODE(OP_SenseHeading,                   0x260a)
OPCODE(OP_Action,                         0x744c)
OPCODE(OP_ConsiderCorpse,                 0x5204)
OPCODE(OP_HideCorpse,                     0x49e1)
OPCODE(OP_CorpseDrag,                     0x0904)
OPCODE(OP_CorpseDrop,                     0x7037)
OPCODE(OP_Bug,                            0x73f4)
OPCODE(OP_Feedback,                       0x5602)
OPCODE(OP_Report,                         0x6f14)
OPCODE(OP_Damage,                         0x6f15)
OPCODE(OP_ChannelMessage,                 0x2b2d)
OPCODE(OP_Assist,                         0x4478)
OPCODE(OP_AssistGroup,                    0x27f8)
OPCODE(OP_MoveCoin,                       0x0bcf)
OPCODE(OP_ZonePlayerToBind,               0x08d8)
OPCODE(OP_KeyRing,                        0x1219)
OPCODE(OP_WhoAllRequest,                  0x674b)
OPCODE(OP_WhoAllResponse,                 0x578c)
OPCODE(OP_FriendsWho,                     0x3956)
OPCODE(OP_ConfirmDelete,                  0x43a3)
OPCODE(OP_Logout,                         0x4ac6)
OPCODE(OP_Rewind,                         0x1745)
OPCODE(OP_TargetCommand,                  0x58e2)
OPCODE(OP_Hide,                           0x67fe)
OPCODE(OP_Jump,                           0x31f4)
OPCODE(OP_Camp,                           0x28ec)
OPCODE(OP_Emote,                          0x373b)
OPCODE(OP_SetRunMode,                     0x009f)
OPCODE(OP_BankerChange,                   0x791e)
OPCODE(OP_TargetMouse,                    0x075d)
OPCODE(OP_MobHealth,                      0x37b1)
OPCODE(OP_InitialMobHealth,               0x0000)  // Unused?
OPCODE(OP_TargetHoTT,                     0x0272)
OPCODE(OP_TargetBuffs,                    0x4f4b)
OPCODE(OP_XTargetResponse,                0x4d59)
OPCODE(OP_XTargetRequest,                 0x3763)
OPCODE(OP_XTargetAutoAddHaters,           0x672f)
OPCODE(OP_XTargetOpen,                    0x61df)
OPCODE(OP_XTargetOpenResponse,            0x3ef8)
OPCODE(OP_BuffCreate,                     0x3377)
OPCODE(OP_BuffRemoveRequest,              0x64f2)
OPCODE(OP_DeleteSpawn,                    0x7280)
OPCODE(OP_AutoAttack,                     0x109d)
OPCODE(OP_AutoAttack2,                    0x3526)
OPCODE(OP_Consume,                        0x4b70)
OPCODE(OP_MoveItem,                       0x32ee)
OPCODE(OP_MoveMultipleItems,              0x5623)
OPCODE(OP_DeleteItem,                     0x18ad)
OPCODE(OP_DeleteCharge,                   0x01b8)
OPCODE(OP_ItemPacket,                     0x368e)
OPCODE(OP_ItemLinkResponse,               0x70c0)
OPCODE(OP_ItemLinkClick,                  0x4cef)
OPCODE(OP_ItemPreview,                    0x6b5c)
OPCODE(OP_NewSpawn,                       0x6097)
OPCODE(OP_Track,                          0x17e5)
OPCODE(OP_TrackTarget,                    0x695e)
OPCODE(OP_TrackUnknown,                   0x4577)
OPCODE(OP_ClickDoor,                      0x3a8f)
OPCODE(OP_MoveDoor,                       0x08e8)
OPCODE(OP_RemoveAllDoors,                 0x700c)
OPCODE(OP_EnvDamage,                      0x51fd)
OPCODE(OP_BoardBoat,                      0x4211)
OPCODE(OP_LeaveBoat,                      0x7617)
OPCODE(OP_ControlBoat,                    0x0ae7)
OPCODE(OP_Forage,                         0x5306)
OPCODE(OP_SafeFallSuccess,                0x2219)
OPCODE(OP_RezzComplete,                   0x760d)
OPCODE(OP_RezzRequest,                    0x3c21)
OPCODE(OP_RezzAnswer,                     0x701c)
OPCODE(OP_Shielding,                      0x52e5)
OPCODE(OP_RequestDuel,                    0x3af1)
OPCODE(OP_MobRename,                      0x2c57)
OPCODE(OP_AugmentItem,                    0x661b)
OPCODE(OP_WeaponEquip1,                   0x34a7)
OPCODE(OP_PlayerStateAdd,                 0x559a)
OPCODE(OP_PlayerStateRemove,              0x2d25)
OPCODE(OP_ApplyPoison,                    0x31e6)
OPCODE(OP_Save,                           0x4a39)
OPCODE(OP_TestBuff,                       0x7cb8)
OPCODE(OP_CustomTitles,                   0x100e)
OPCODE(OP_Split,                          0x3a54)
OPCODE(OP_YellForHelp,                    0x4e56)
OPCODE(OP_LoadSpellSet,                   0x261d)
OPCODE(OP_Bandolier,                      0x7677)
OPCODE(OP_PotionBelt,                     0x1a3e)
OPCODE(OP_DuelDecline,                    0x6a46)
OPCODE(OP_DuelAccept,                     0x68d3)
OPCODE(OP_SaveOnZoneReq,                  0x600d)
OPCODE(OP_ReadBook,                       0x72df)
OPCODE(OP_Dye,                            0x23b9)
OPCODE(OP_InterruptCast,                  0x048c)
OPCODE(OP_AAAction,                       0x424e)
OPCODE(OP_LeadershipExpToggle,            0x74bd)
OPCODE(OP_LeadershipExpUpdate,            0x2797)
OPCODE(OP_PurchaseLeadershipAA,           0x6c55)
OPCODE(OP_UpdateLeadershipAA,             0x0026)
OPCODE(OP_MarkNPC,                        0x1fb5)
OPCODE(OP_ClearNPCMarks,                  0x2003)
OPCODE(OP_DelegateAbility,                0x76b8)
OPCODE(OP_SetGroupTarget,                 0x2814)
OPCODE(OP_Charm,                          0x5d92)
OPCODE(OP_Stun,                           0x36a4)
OPCODE(OP_SendFindableNPCs,               0x4613)
OPCODE(OP_FindPersonRequest,              0x5cea)
OPCODE(OP_FindPersonReply,                0x7e58)
OPCODE(OP_Sound,                          0x1a30)
OPCODE(OP_CashReward,                     0x5f7a)
OPCODE(OP_PetBuffWindow,                  0x5882)
OPCODE(OP_LevelAppearance,                0x3bc9)
OPCODE(OP_Translocate,                    0x6580)
OPCODE(OP_Sacrifice,                      0x1821)
OPCODE(OP_PopupResponse,                  0x08a6)
OPCODE(OP_OnLevelMessage,                 0x575b)
OPCODE(OP_AugmentInfo,                    0x0afb)
OPCODE(OP_Petition,                       0x3de3)
OPCODE(OP_SomeItemPacketMaybe,            0x747c)
OPCODE(OP_PVPStats,                       0x4b15)
OPCODE(OP_PVPLeaderBoardRequest,          0x04aa)
OPCODE(OP_PVPLeaderBoardReply,            0x071f)
OPCODE(OP_PVPLeaderBoardDetailsRequest,   0x3707)
OPCODE(OP_PVPLeaderBoardDetailsReply,     0x25b7)
OPCODE(OP_RestState,                      0x000f)
OPCODE(OP_RespawnWindow,                  0x0ecb)
OPCODE(OP_LDoNButton,                     0x5327)
OPCODE(OP_SetStartCity,                   0x6326)
OPCODE(OP_VoiceMacroIn,                   0x17fd)
OPCODE(OP_VoiceMacroOut,                  0x409a)
OPCODE(OP_ItemViewUnknown,                0x465b)
OPCODE(OP_VetRewardsAvaliable,            0x590e)
OPCODE(OP_VetClaimRequest,                0x1126)
OPCODE(OP_VetClaimReply,                  0x16d4)
OPCODE(OP_DisciplineUpdate,               0x759e)
OPCODE(OP_DisciplineTimer,                0x6989)
OPCODE(OP_BecomeCorpse,                   0x0000)  // Unused?
OPCODE(OP_Action2,                        0x0000)  // Unused?
OPCODE(OP_MobUpdate,                      0x2c84)
OPCODE(OP_NPCMoveUpdate,                  0x5892)
OPCODE(OP_CameraEffect,                   0x127f)
OPCODE(OP_SpellEffect,                    0x5936)
OPCODE(OP_AddNimbusEffect,                0xc693)
OPCODE(OP_RemoveNimbusEffect,             0x7b1e)
OPCODE(OP_AltCurrency,                    0x6b6d)
OPCODE(OP_AltCurrencyMerchantRequest,     0x5409)
OPCODE(OP_AltCurrencyMerchantReply,       0x27a2)
OPCODE(OP_AltCurrencyPurchase,            0x3788)
OPCODE(OP_AltCurrencySell,                0x40b6)
OPCODE(OP_AltCurrencySellSelection,       0x532a)
OPCODE(OP_AltCurrencyReclaim,             0x0339)
OPCODE(OP_CrystalCountUpdate,             0x467f)
OPCODE(OP_CrystalCreate,                  0x7aee)
OPCODE(OP_CrystalReclaim,                 0x2439)
OPCODE(OP_Untargetable,                   0x053c)
OPCODE(OP_IncreaseStats,                  0x70a3)
OPCODE(OP_Weblink,                        0x6f4b)
OPCODE(OP_OpenContainer,                  0x0000)
OPCODE(OP_Marquee,                        0x502e)
OPCODE(OP_ItemRecastDelay,                0x15a9)
//OPCODE(OP_OpenInventory,                  0x0000)  // Likely does not exist in RoF -U
OPCODE(OP_ResetAA,                        0x1669)
OPCODE(OP_Fling,                          0x6f80)
OPCODE(OP_CancelSneakHide,                0x0927)
OPCODE(OP_AggroMeterLockTarget,           0x1643)
OPCODE(OP_AggroMeterTargetInfo,           0x16bc)
OPCODE(OP_AggroMeterUpdate,               0x1781)
OPCODE(OP_UnderWorld,                     0x2eb3)  // clients sends up when they detect an underworld issue, might be useful for cheat detection
OPCODE(OP_KickPlayers,                    0x6770)
OPCODE(OP_BookButton,                     0x6146)

// Expeditions
OPCODE(OP_DzQuit,                         0xb2e3)
OPCODE(OP_DzListTimers,                   0x7b68)
OPCODE(OP_DzAddPlayer,                    0x4701)
OPCODE(OP_DzRemovePlayer,                 0x1abc)
OPCODE(OP_DzSwapPlayer,                   0x405b)
OPCODE(OP_DzMakeLeader,                   0x543d)
OPCODE(OP_DzPlayerList,                   0x14c6)
OPCODE(OP_DzExpeditionInvite,             0x7f4b)
OPCODE(OP_DzExpeditionInviteResponse,     0x1950)
OPCODE(OP_DzExpeditionInfo,               0x9119)
OPCODE(OP_DzExpeditionLockoutTimers,      0x205f)
OPCODE(OP_DzMemberList,                   0x5ae4)
OPCODE(OP_DzMemberListName,               0x32f0)
OPCODE(OP_DzMemberListStatus,             0x12F5)
OPCODE(OP_DzSetLeaderName,                0x3de9)
OPCODE(OP_DzExpeditionEndsWarning,        0x5189)
OPCODE(OP_DzCompass,                      0x3e0e)
OPCODE(OP_DzChooseZone,                   0x0b7d)
OPCODE(OP_DzChooseZoneReply,              0x4de1)

// New Opcodes
OPCODE(OP_SpawnPositionUpdate,            0x0000)  // Actually OP_MobUpdate ?
OPCODE(OP_ManaUpdate,                     0x3791)
OPCODE(OP_EnduranceUpdate,                0x5f42)
OPCODE(OP_MobManaUpdate,                  0x2404)
OPCODE(OP_MobEnduranceUpdate,             0x1c81)

// Mercenary Opcodes
OPCODE(OP_MercenaryDataUpdateRequest,     0x7b89)
OPCODE(OP_MercenaryDataUpdate,            0x61a4)
OPCODE(OP_MercenaryDataRequest,           0x11c1)
OPCODE(OP_MercenaryDataResponse,          0x72ce)
OPCODE(OP_MercenaryHire,                  0x7169)
OPCODE(OP_MercenaryDismiss,               0x6e83)
OPCODE(OP_MercenaryTimerRequest,          0x31e4)
OPCODE(OP_MercenaryTimer,                 0x0763)
OPCODE(OP_MercenaryUnknown1,              0x5d26)
OPCODE(OP_MercenaryCommand,               0x27f2)
OPCODE(OP_MercenarySuspendRequest,        0x4407)
OPCODE(OP_MercenarySuspendResponse,       0x6f03)
OPCODE(OP_MercenaryUnsuspendResponse,     0x27a0)

// Looting
OPCODE(OP_LootRequest,                    0x0adf)
OPCODE(OP_EndLootRequest,                 0x30f7)
OPCODE(OP_LootItem,                       0x4dc9)
OPCODE(OP_LootComplete,                   0x55c4)

// bazaar trader stuff:
OPCODE(OP_BazaarSearch,                   0x39d6)
OPCODE(OP_TraderDelItem,                  0x5829)
OPCODE(OP_BecomeTrader,                   0x61b3)
OPCODE(OP_TraderShop,                     0x31df)
OPCODE(OP_TraderBulkSend,                 0x6a96)
OPCODE(OP_Trader,                         0x4ef5)
OPCODE(OP_Barter,                         0x243a)
OPCODE(OP_BuyerItems,                     0x1a6a)
OPCODE(OP_TraderBuy,                      0x0000)
OPCODE(OP_ShopItem,                       0x0000)
OPCODE(OP_BazaarInspect,                  0x0000)
OPCODE(OP_Bazaar,                         0x0000)
OPCODE(OP_TraderItemUpdate,               0x0000)

// pc/npc trading
OPCODE(OP_TradeRequest,                   0x77b5)
OPCODE(OP_TradeAcceptClick,               0x69e2)
OPCODE(OP_TradeRequestAck,                0x14bf)
OPCODE(OP_TradeCoins,                     0x4206)
OPCODE(OP_FinishTrade,                    0x3993)
OPCODE(OP_CancelTrade,                    0x354c)
OPCODE(OP_TradeMoneyUpdate,               0x68c2)
OPCODE(OP_MoneyUpdate,                    0x640c)
OPCODE(OP_TradeBusy,                      0x5505)

// Sent after canceling trade or after closing tradeskill object
OPCODE(OP_FinishWindow,                   0x7349)
OPCODE(OP_FinishWindow2,                  0x40ef)

// Sent on Live for what seems to be item existance verification
// Ex. Before Right Click Effect happens from items
OPCODE(OP_ItemVerifyRequest,              0x189c)
OPCODE(OP_ItemVerifyReply,                0x097b)

//OPCODE(OP_ItemAdvancedLoreText,           0x023b)

// merchant stuff
OPCODE(OP_ShopPlayerSell,                 0x791b)
OPCODE(OP_ShopRequest,                    0x4fed)
OPCODE(OP_ShopEnd,                        0x30a8)
OPCODE(OP_ShopEndConfirm,                 0x3196)
OPCODE(OP_ShopPlayerBuy,                  0x0ddd)
OPCODE(OP_ShopDelItem,                    0x724f)
OPCODE(OP_ShopSendParcel,                 0x3a5d)
OPCODE(OP_ShopDeleteParcel,               0x47f1)
OPCODE(OP_ShopRetrieveParcel,             0x7013)
OPCODE(OP_ShopParcelIcon,                 0x46f0)

// tradeskill stuff:
OPCODE(OP_ClickObject,                    0x4aa1)
OPCODE(OP_ClickObjectAction,              0x0c1e)
OPCODE(OP_ClearObject,                    0x7a11)
OPCODE(OP_RecipeDetails,                  0x6e02)
OPCODE(OP_RecipesFavorite,                0x71b1)
OPCODE(OP_RecipesSearch,                  0x6290)
OPCODE(OP_RecipeReply,                    0x1db6)
OPCODE(OP_RecipeAutoCombine,              0x40d7)
OPCODE(OP_TradeSkillCombine,              0x579a)

// Tribute Packets:
OPCODE(OP_OpenTributeMaster,              0x7666)
OPCODE(OP_SelectTribute,                  0x79fc)
OPCODE(OP_TributeItem,                    0x4f3e)
OPCODE(OP_TributeMoney,                   0x58fb)
OPCODE(OP_TributeToggle,                  0x241d)
OPCODE(OP_TributePointUpdate,             0x5300)
OPCODE(OP_TributeNPC,                     0x0000)
OPCODE(OP_GuildTributeInfo,               0x0000)
//OPCODE(OP_OpenTributeReply,               0x0000)
//OPCODE(OP_GuildTributeStatus,             0x0000)
OPCODE(OP_GuildSaveActiveTributes,        0x5f3f)
OPCODE(OP_GuildSendActiveTributes,        0x3771)
OPCODE(OP_GuildTributeToggleReq,          0x7745)
OPCODE(OP_GuildTributeToggleReply,        0x20ae)
OPCODE(OP_GuildTributeFavorAndTimer,      0x7fe0)
OPCODE(OP_GuildTributeDonateItem,         0x5bcb)
OPCODE(OP_GuildTributeDonatePlat,         0x43d2)
OPCODE(OP_GuildSelectTribute,             0x649f)
OPCODE(OP_GuildModifyBenefits,            0x34cd)
OPCODE(OP_GuildOptInOut,                  0x0727)
OPCODE(OP_SendGuildTributes,              0x1877)
OPCODE(OP_OpenGuildTributeMaster,         0x49ea)

// Adventure packets:
OPCODE(OP_LeaveAdventure,                 0x5d18)
OPCODE(OP_AdventureFinish,                0x400f)
OPCODE(OP_AdventureInfoRequest,           0x3cb0)
OPCODE(OP_AdventureInfo,                  0x4c54)
OPCODE(OP_AdventureRequest,               0x2c6c)
OPCODE(OP_AdventureDetails,               0x5648)
OPCODE(OP_AdventureData,                  0x7171)
OPCODE(OP_AdventureUpdate,                0x1b01)
OPCODE(OP_AdventureMerchantRequest,       0x6922)
OPCODE(OP_AdventureMerchantResponse,      0x3e47)
OPCODE(OP_AdventureMerchantPurchase,      0x5b72)
OPCODE(OP_AdventureMerchantSell,          0x2f9b)
OPCODE(OP_AdventurePointsUpdate,          0x65c3)
OPCODE(OP_AdventureStatsRequest,          0x5a62)
OPCODE(OP_AdventureStatsReply,            0x2370)
OPCODE(OP_AdventureLeaderboardRequest,    0x7093)
OPCODE(OP_AdventureLeaderboardReply,      0x7f79)

// Group Opcodes
OPCODE(OP_GroupDisband,                   0x4c10)
OPCODE(OP_GroupInvite,                    0x6110)
OPCODE(OP_GroupFollow,                    0x1649)
OPCODE(OP_GroupUpdate,                    0x3abb)
OPCODE(OP_GroupUpdateB,                   0x6194)
OPCODE(OP_GroupCancelInvite,              0x0000)
OPCODE(OP_GroupAcknowledge,               0x7323)
OPCODE(OP_GroupDelete,                    0x0f6c)
//OPCODE(OP_CancelInvite,                   0x2a50)
OPCODE(OP_GroupFollow2,                   0x2060)
OPCODE(OP_GroupInvite2,                   0x32c2)
OPCODE(OP_GroupDisbandYou,                0x1ae5)
OPCODE(OP_GroupDisbandOther,              0x74da)
OPCODE(OP_GroupLeaderChange,              0x21b4)
OPCODE(OP_GroupRoles,                     0x70e2)
OPCODE(OP_GroupMakeLeader,                0x4229)
OPCODE(OP_DoGroupLeadershipAbility,       0x6eae)
OPCODE(OP_GroupLeadershipAAUpdate,        0x02cf)
OPCODE(OP_GroupMentor,                    0x3342)
OPCODE(OP_InspectBuffs,                   0x486c)

// LFG/LFP Opcodes
OPCODE(OP_LFGCommand,                     0x6060)
OPCODE(OP_LFGGetMatchesRequest,           0x0340)
OPCODE(OP_LFGGetMatchesResponse,          0x5048)
OPCODE(OP_LFPGetMatchesRequest,           0x4d7d)
OPCODE(OP_LFPGetMatchesResponse,          0x22c6)
OPCODE(OP_LFPCommand,                     0x49a9)
OPCODE(OP_LFGAppearance,                  0x0000)
OPCODE(OP_LFGResponse,                    0x0000)

// Raid Opcodes
OPCODE(OP_RaidInvite,                     0x55ac)
OPCODE(OP_RaidUpdate,                     0x3973)
OPCODE(OP_RaidJoin,                       0x0000)
OPCODE(OP_RaidDelegateAbility,            0x2b33)
OPCODE(OP_MarkRaidNPC,                    0x5a58)
OPCODE(OP_RaidClearNPCMarks,              0x20d3)

// Button-push commands
OPCODE(OP_Taunt,                          0x2703)
OPCODE(OP_CombatAbility,                  0x3eba)
OPCODE(OP_SenseTraps,                     0x02af)
OPCODE(OP_PickPocket,                     0x39e8)
OPCODE(OP_DisarmTraps,                    0x78bf)
OPCODE(OP_Disarm,                         0x5ec8)
OPCODE(OP_Sneak,                          0x5d55)
OPCODE(OP_Fishing,                        0x1e2a)
OPCODE(OP_InstillDoubt,                   0x640e)
OPCODE(OP_FeignDeath,                     0x52fa)
OPCODE(OP_Mend,                           0x0ecf)
OPCODE(OP_Bind_Wound,                     0x0386)
OPCODE(OP_LDoNOpen,                       0x3d5c)
//OPCODE(OP_LDoNDisarmTraps,                0x0000)  // Same as OP_DisarmTraps in RoF
OPCODE(OP_LDoNPickLock,                   0x9be3)
OPCODE(OP_LDoNInspect,                    0x0438)

// Task packets
OPCODE(OP_TaskDescription,                0x3714)
OPCODE(OP_TaskActivity,                   0x08d3)
OPCODE(OP_CompletedTasks,                 0x4eba)
OPCODE(OP_TaskActivityComplete,           0x5e19)
OPCODE(OP_AcceptNewTask,                  0x0a23)
OPCODE(OP_CancelTask,                     0x39f0)
//OPCODE(OP_AvaliableTask,                  0x36e8)
OPCODE(OP_TaskHistoryRequest,             0x5f1c)
OPCODE(OP_TaskHistoryReply,               0x3d05)
//OPCODE(OP_DeclineAllTasks,                0x0000)
OPCODE(OP_TaskRequestTimer,               0x7a48)
OPCODE(OP_TaskSelectWindow,               0x705b)

// Shared Tasks
OPCODE(OP_SharedTaskMemberList,           0x1e7d)
OPCODE(OP_SharedTaskRemovePlayer,         0x4865)  // /taskremoveplayer
OPCODE(OP_SharedTaskAddPlayer,            0x36e8)  // /taskaddplayer
OPCODE(OP_SharedTaskMakeLeader,           0x37f2)  // /taskmakeleader
OPCODE(OP_SharedTaskInvite,               0x3444)  // Dialog window
OPCODE(OP_SharedTaskInviteResponse,       0x7582)  // Dialog window response
OPCODE(OP_SharedTaskAcceptNew,            0x6646)
OPCODE(OP_SharedTaskMemberChange,         0x0119)
OPCODE(OP_TaskTimers,                     0x2b0f)  // /tasktimers
OPCODE(OP_SharedTaskQuit,                 0x322e)  // /taskquit
OPCODE(OP_SharedTaskSelectWindow,         0x48a2)
OPCODE(OP_SharedTaskPlayerList,           0x5727)  // /taskplayerlist

// Title opcodes
OPCODE(OP_NewTitlesAvailable,             0x0d32)
OPCODE(OP_RequestTitles,                  0x6344)
OPCODE(OP_SendTitleList,                  0x2d08)
OPCODE(OP_SetTitle,                       0x6527)
OPCODE(OP_SetTitleReply,                  0x4c21)

// mail opcodes
OPCODE(OP_Command,                        0x0000)
//OPCODE(OP_MailboxHeader,                  0x0000)
OPCODE(OP_MailHeader,                     0x0000)
//OPCODE(OP_MailBody,                       0x0000)
//OPCODE(OP_NewMail,                        0x0000)
//OPCODE(OP_SentConfirm,                    0x0000)

// ########### Below this point should not be needed ###########

// This section are all unknown in Titanium
OPCODE(OP_ForceFindPerson,                0x0000)
OPCODE(OP_LocInfo,                        0x0000)
OPCODE(OP_ReloadUI,                       0x0000)
OPCODE(OP_ItemName,                       0x0000)
OPCODE(OP_ItemLinkText,                   0x0000)
OPCODE(OP_MultiLineMsg,                   0x0000)
OPCODE(OP_MendHPUpdate,                   0x0000)
OPCODE(OP_TargetReject,                   0x0000)
OPCODE(OP_SafePoint,                      0x0000)
OPCODE(OP_ApproveZone,                    0x0000)
OPCODE(OP_ZoneComplete,                   0x0000)
OPCODE(OP_ClientError,                    0x0000)
OPCODE(OP_DumpName,                       0x0000)
OPCODE(OP_Heartbeat,                      0x0000)
OPCODE(OP_CrashDump,                      0x0000)
OPCODE(OP_LoginComplete,                  0x0000)

// discovered opcodes not yet used:
//OPCODE(OP_PickLockSuccess,                0x0000)
OPCODE(OP_PlayMP3,                        0x5770)
OPCODE(OP_ReclaimCrystals,                0x0000)
OPCODE(OP_DynamicWall,                    0x0000)
OPCODE(OP_OpenDiscordMerchant,            0x0000)
OPCODE(OP_DiscordMerchantInventory,       0x0000)
OPCODE(OP_GiveMoney,                      0x0000)
OPCODE(OP_RequestKnowledgeBase,           0x0000)
OPCODE(OP_KnowledgeBase,                  0x0000)
//OPCODE(OP_SlashAdventure,                 0x0000)  // /adventure
//OPCODE(OP_BecomePVPPrompt,                0x0000)
OPCODE(OP_MoveLogRequest,                 0x0000)  // gone I think
OPCODE(OP_MoveLogDisregard,               0x0000)  // gone I think

// named unknowns, to make looking for real unknown easier
OPCODE(OP_AnnoyingZoneUnknown,            0x0000)
OPCODE(OP_Some6ByteHPUpdate,              0x0000) // seems to happen when you target group members
OPCODE(OP_QueryResponseThing,             0x0000)

// realityincarnate: these are just here to stop annoying several thousand byte packet dumps
//OPCODE(OP_LoginUnknown1,                  0x46d3) // OP_SendSpellChecksum
//OPCODE(OP_LoginUnknown2,                  0x040b) // OP_SendSkillCapsChecksum

// Petition Opcodes
OPCODE(OP_PetitionSearch,                 0x0000)  // search term for petition
OPCODE(OP_PetitionSearchResults,          0x0000)  // (list of?) matches from search
OPCODE(OP_PetitionSearchText,             0x0000)  // text results of search

OPCODE(OP_PetitionUpdate,                 0x0000)
OPCODE(OP_PetitionCheckout,               0x0000)
OPCODE(OP_PetitionCheckIn,                0x0000)
OPCODE(OP_PetitionQue,                    0x0000)
OPCODE(OP_PetitionUnCheckout,             0x0000)
OPCODE(OP_PetitionDelete,                 0x0000)
OPCODE(OP_DeletePetition,                 0x0000)
OPCODE(OP_PetitionResolve,                0x0000)
OPCODE(OP_PDeletePetition,                0x0000)
OPCODE(OP_PetitionBug,                    0x0000)
OPCODE(OP_PetitionRefresh,                0x0000)
OPCODE(OP_PetitionCheckout2,              0x0000)
//OPCODE(OP_PetitionViewPetition,           0x0000)

// Login opcodes
OPCODE(OP_SessionReady,                   0x0000)
OPCODE(OP_Login,                          0x0000)
OPCODE(OP_ServerListRequest,              0x0000)
OPCODE(OP_PlayEverquestRequest,           0x0000)
OPCODE(OP_PlayEverquestResponse,          0x0000)
OPCODE(OP_ChatMessage,                    0x0000)
OPCODE(OP_LoginAccepted,                  0x0000)
OPCODE(OP_ServerListResponse,             0x0000)
OPCODE(OP_Poll,                           0x0000)
OPCODE(OP_EnterChat,                      0x0000)
OPCODE(OP_PollResponse,                   0x0000)

// raw opcodes
//OPCODE(OP_RAWSessionRequest,              0x0000)
//OPCODE(OP_RAWSessionResponse,             0x0000)
//OPCODE(OP_RAWCombined,                    0x0000)
//OPCODE(OP_RAWSessionDisconnect,           0x0000)
//OPCODE(OP_RAWKeepAlive,                   0x0000)
//OPCODE(OP_RAWSessionStatRequest,          0x0000)
//OPCODE(OP_RAWSessionStatResponse,         0x0000)
//OPCODE(OP_RAWPacket,                      0x0000)
//OPCODE(OP_RAWFragment,                    0x0000)
//OPCODE(OP_RAWOutOfOrderAck,               0x0000)
//OPCODE(OP_RAWAck,                         0x0000)
//OPCODE(OP_RAWAppCombined,                 0x0000)
//OPCODE(OP_RAWOutOfSession,                0x0000)

// we need to document the differences between these packets to make identifying them easier
OPCODE(OP_Some3ByteHPUpdate,              0x0000)  // initial HP update for mobs
OPCODE(OP_InitialHPUpdate,                0x0000)

// aura related
OPCODE(OP_UpdateAura,                     0x1456)
OPCODE(OP_RemoveTrap,                     0x71da)
