FROM mcr.microsoft.com/devcontainers/base:debian AS base
RUN sudo apt update \
	&& sudo apt install -y --no-install-recommends \
		autoconf \
		automake \
		build-essential \
		ccache \
		clang \
		clang-tools \
		cmake \
		curl \
		debconf-utils \
		gdb \
		git \
		google-perftools \
		iputils-ping \
		libtool \
		linux-libc-dev \
		locales \
		make \
		mariadb-client \
		mariadb-server \
		minizip \
		nano \
		ninja-build \
		open-vm-tools \
		pv \
		sudo \
		telnet \
		unzip \
		valgrind \
		wget


FROM base AS devcontainer

# This is a "dev" image for running eqemu in development, also for dev containers
ARG REMOTE_USER
ARG REMOTE_UID
ARG REMOTE_GID

# Create the user
RUN echo "Creating user $REMOTE_USER with UID $REMOTE_UID and GID $REMOTE_GID a"
RUN groupmod -g 1001 vscode && usermod -u 1001 -g 1001 vscode
RUN groupadd --gid $REMOTE_UID $REMOTE_USER
RUN useradd --uid $REMOTE_UID --gid $REMOTE_GID -m $REMOTE_USER
RUN echo $REMOTE_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$REMOTE_USER
RUN chmod 0440 /etc/sudoers.d/$REMOTE_USER

USER ${REMOTE_USER}
