FROM mcr.microsoft.com/devcontainers/base:debian as base
RUN sudo apt update \
	&& sudo apt install -y --no-install-recommends \
		build-essential \
		libtool \
		cmake \
		curl \
		debconf-utils \
		git \
		libluabind-dev \
		libsodium-dev \
		liblua5.2-0 \
		liblua5.2-dev \
		libmariadb-dev \
		libssl-dev \
		minizip \
		make \
		mariadb-client \
		locales \
		nano \
		open-vm-tools \
		unzip \
		uuid-dev \
		iputils-ping \
		wget \
		libcurl4-openssl-dev \
		gdb \
		libyaml-cpp-dev \
		ccache \
		ninja-build \
		pv \
		mariadb-server \
		libperl-dev \
		libjson-perl \
		libio-stringy-perl \
		liblua5.1-dev \
		libluabind-dev \
		libboost-dev \
		mariadb-server \
		valgrind \
		telnet \
		libgoogle-perftools-dev \
		google-perftools


FROM base as devcontainer

# This is a "dev" image for running eqemu in development, also for dev containers
ARG REMOTE_USER
ARG REMOTE_UID
ARG REMOTE_GID

RUN <<EOF
	addgroup --gid ${REMOTE_GID} ${REMOTE_USER}
	adduser --disabled-password --uid ${REMOTE_UID} --gid ${REMOTE_GID} ${REMOTE_USER}
EOF

ENV HOME /home/${REMOTE_USER}
USER ${REMOTE_USER}
